import { z } from 'zod';
import { coordinateSystemSchema, serviceNames } from './serviceCommonTypes';

export const sportFontSchema = z.union([z.literal('classic'), z.intersection(z.string(), z.object({}))]);

export const scoreBoardSchema = z.object({
    id: z.number().nonnegative(),
    enabled: z.union([z.literal(0), z.literal(1)]),
    schedule: z.string().optional(),
    cameraList: z.array(z.number()),
    zIndex: z.number().nonnegative(),
    name: z.literal(serviceNames.scoreBoard),
    pos_x: z.number(),
    pos_y: z.number(),
    coordSystem: coordinateSystemSchema,
    width: z.number(),
    height: z.number(),
    scale: z.number(),
    teamHomeShortname: z.string(),
    teamGuestShortname: z.string(),
    teamHomeBackgroundColor: z.string(),
    teamGuestBackgroundColor: z.string(),
    teamHomeTextColor: z.string(),
    teamGuestTextColor: z.string(),
    teamHomeImgPath: z.string(),
    teamGuestImgPath: z.string(),
    teamHomeCurrentScore: z.number(),
    teamGuestCurrentScore: z.number(),
    baseTimeTimestamp: z.number(),
    baseTimePlaytime: z.number(),
    currentPeriodPlaytime: z.number(),
    timeIsRunning: z.boolean(),
    currentPeriodLength: z.number(),
    currentPeriod: z.number(),
    font: sportFontSchema.default('classic'),
});

export const baseballScoreBoardSchema = z.object({
    id: z.number().nonnegative(),
    enabled: z.union([z.literal(0), z.literal(1)]),
    schedule: z.string().optional(),
    cameraList: z.array(z.number()),
    zIndex: z.number().nonnegative(),
    name: z.literal(serviceNames.baseballScoreBoard),
    pos_x: z.number(),
    pos_y: z.number(),
    coordSystem: coordinateSystemSchema,
    width: z.number(),
    height: z.number(),
    scale: z.number(),

    matchFinished: z.boolean(),
    bases: z.tuple([z.boolean(), z.boolean(), z.boolean()]),
    homeInning: z.boolean(),
    inning: z.number().nonnegative(),
    outs: z.number().nonnegative(),
    balls: z.number().nonnegative(),
    strikes: z.number().nonnegative(),
    baseTimeTimestamp: z.number(),
    baseTimePlaytime: z.number(),
    timeIsRunning: z.boolean(),

    teamHomeShortname: z.string(),
    teamGuestShortname: z.string(),
    teamHomeBackgroundColor: z.string(),
    teamGuestBackgroundColor: z.string(),
    teamHomeTextColor: z.string(),
    teamGuestTextColor: z.string(),
    teamHomeCurrentScore: z.number(),
    teamGuestCurrentScore: z.number(),
    footerImgPath: z.string().optional(),
    footerText: z.string().optional(),
    footerBackgroundColor: z.string().optional(),
    footerTextColor: z.string().optional(),

    font: sportFontSchema.default('classic'),
});

export const baseballScoreBoardAutomaticSchema = z.object({
    id: z.number().nonnegative(),
    enabled: z.union([z.literal(0), z.literal(1)]),
    schedule: z.string().optional(),
    cameraList: z.array(z.number()),
    zIndex: z.number().nonnegative(),
    name: z.literal(serviceNames.myBallBaseballWidgets),
    width: z.number(),
    height: z.number(),
    scale: z.number(),

    matchDetailLink: z.string(),
    matchListLink: z.string(),
    mirrored: z.boolean(),
    pregameWidgetText: z.string(),

    teamHomeBackgroundColor: z.string(),
    teamGuestBackgroundColor: z.string(),
    teamHomeTextColor: z.string(),
    teamGuestTextColor: z.string(),
    homeLogoPath: z.string(),
    guestLogoPath: z.string(),

    footerImgPath: z.string().optional(),
    footerText: z.string().optional(),
    footerBackgroundColor: z.string().optional(),
    footerTextColor: z.string().optional(),

    font: sportFontSchema.default('classic'),
});

export const scoreOverviewSchema = z.object({
    id: z.number().nonnegative(),
    enabled: z.union([z.literal(0), z.literal(1)]),
    cameraList: z.array(z.number()),
    zIndex: z.number().nonnegative(),
    name: z.literal(serviceNames.scoreOverview),
    pos_x: z.number(),
    pos_y: z.number(),
    coordSystem: coordinateSystemSchema,
    width: z.number(),
    height: z.number(),
    scale: z.number(),
    teamHomeName: z.string(),
    teamGuestName: z.string(),
    teamHomeBackgroundColor: z.string(),
    teamGuestBackgroundColor: z.string(),
    teamHomeTextColor: z.string(),
    teamGuestTextColor: z.string(),
    teamHomeImgPath: z.string(),
    teamGuestImgPath: z.string(),
    teamHomeCurrentScore: z.number(),
    teamGuestCurrentScore: z.number(),
    scoreVisible: z.boolean(),
    description: z.string(),

    textFont: sportFontSchema.default('classic'),
    scoreFont: z.literal('classic'), // Supposed to always be 'classic'
});
